Core\AdminBundle\Entity\ReflisteActivitetache:
    type: entity
    table: refliste_activitetache
    id:
        refIntActivitetache:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: Ref_Int_ActiviteTache
            generator:
                strategy: IDENTITY
    fields:
        activitetache:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: ActiviteTache
    lifecycleCallbacks: {  }
