<?php

namespace Core\AdminBundle\Entity;

use Doctrine\ORM\AbstractQuery;
use Doctrine\DBAL\Logging;
use Doctrine\ORM\Repository;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\DBAL\Configuration;
use Core\AdminBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * admin_listedesreglesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class adminlistedesreglesRepository extends EntityRepository
{
    
 
            
}
