<?php

namespace Core\AdminBundle\Entity;

use Doctrine\ORM\AbstractQuery;
use Doctrine\DBAL\Logging;
use Doctrine\ORM\Repository;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\DBAL\Configuration;
use Core\AdminBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * VerifConnexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerifConnexRepository extends EntityRepository
{
    
    public function getPlusRecent() {
    //    $rep = $this->findAll();
    //    $rep = $this->getDoctrine()->getRepository('CoreAdminBundle:VerifConnex');
    //   $dernierAcces = $rep->findOneById(1);
       
       //return $this->_em->createQuery(' SELECT DateAccess FROM verifconnex WHERE id = 1;')->setParameter('enabled',true);
       
        return Array('name' => "name")  ;    
    }
            
            
}
